config/routes.rb
Project::Application.routes.draw do

  get "site/index"
  get "site/welcome"
  get "sessions/new"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts
  resources :posts do
    resources :comments
  end

   root 'site#welcome'
   get 'welcome' => 'site#welcome'
   get 'sign_up' => 'users#new'
   get 'sign_in' => 'sessions#new'
   get 'sign_out' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post

  validates :body, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	validates :title, :content, presence: true
	validates :title, length: { maximum: 50 }

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, uniqueness: true
	validates :email, presence: true
	validates :name , presence: true
	validates_uniqueness_of :email
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

	def authorize
		if current_user.nil?
			session[:protected_page] = request.fullpath
			redirect_to sign_in_url, alert: 'You must login to view that page.'
		end
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def login(user)
		reset_session
		session[:user_id] = user.id
	end

	def logout
		reset_session
		session[:user_id] = nil
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize
	before_action :set_post
	before_action :set_comment, only: [:show, :edit, :update, :destroy]
  def index
  	@comments = @post.comments
    redirect_to post_path(@post)

  end

  def new
  	@comment = @post.comments.build
  end

  def create
  	@comment = @post.comments.build(comment_params)
  	if @comment.save
  		redirect_to post_comments_path(@post), notice: 'comment created'
  	else 
  		render :new
  	end
  end

  def show
  end

  def edit
  end

  def update
  	if @comment.update_attributes(comment_params)
  			redirect_to post_comments_path(@post), notice: 'Comment Updated'
  	else
  		render :edit
  	end
  end

  def destroy
  	@comment.destroy
  	redirect_to post_comments_path(@post), notice: 'Comment Deleted'
  end

private
	
	def set_post
		@post = Post.find(params[:post_id])
	end

	def set_comment
		@comment = @post.comments.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit(:body)
	end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
  	@posts = Post.all
  end
  def new 
  		@post = Post.new
  end

  def show
  end

  def create
  		@post = Post.new(post_params)
  		if @post.save
  				redirect_to @post, notice: 'It is posted'
  		else 
  				render 'new'
  		end
  end
  def edit
  end

  def update 
  		@post.update_attributes(post_params)
  		if @post.save 
  			redirect_to @post, notice: 'Post is updated.'
  		else
  			render 'edit'
  		end
  end

  def destroy
  		@post.destroy
  		redirect_to posts_path, notice: 'The post is deleted'
  end



private
	def post_params
			params.require(:post).permit(:title, :content, :date)
	end

	def set_post
			@post = Post.find(params[:id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  		user = User.find_by_email(params[:email])
  		if user && user.authenticate(params[:password])

  		  redirect_path = root_path
        
  		  if session[:protected_page]
  			 redirect_path = session[:protected_page]
  			 session[:protected_page] = nil
  		  end
  			 login(user)
  			 redirect_to redirect_path, notice: 'Logged In'
  		  else
  			   redirect_to sign_in_path, alert: 'Invalid Email/Password'
  		end
        
  end
      

	def destroy
		logout
		redirect_to root_path, notice: 'Logged Out!'
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def about
  end

  def welcome
  	if current_user
  		redirect_to posts_path
  	else
  		redirect_to sign_in_path
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new 
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			login(@user)
			redirect_to root_path, notice: 'You are signed up'
		else 
			render :new
		end
end

private 
	def user_params
		params.require(:user).permit( :name, :email,:password,:password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
        def self.included(base)
            ActionView::Base.default_form_builder = StandardBuilder
        end

        class StandardBuilder < ActionView::Helpers::FormBuilder
                def error_messages(options = {})
                        return unless object.respond_to?(:errors) && object.errors.any?

                        if options[:error_message].nil?  
                                errors_title = @template.content_tag(:h3, "Please fix the following errors:", class: "error-title")
                        else
                                errors_title = @template.content_tag(:h3, options[:error_message], class: "error-title")
                        end
                        errors_list = ""
                        errors_list << object.errors.full_messages.map { |message| @template.content_tag(:li, message) }.join("\n")

                        error_messages = @template.content_tag(:ul, errors_list.html_safe, class: "error-messages")

                        @template.content_tag(:div, errors_title+error_messages, class: "form-errors")
                end

        end
end

app/helpers/layout_helper.rb
module LayoutHelper
	def title (page_title, show_title = true)
		content_for(:title) {page_title.to_s}
		@show_title = show_title
	end

	def show_title?
		@show_title
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
	def title(page_title, show_title= true)
		content_for(:title) {page_title.to_s }
		@show_title = show_title
	end

	def show_title?
		@show_title
	end

	def nav_link(text,path)
		if current_page?(path)
			content_tag :li, link_to(text, path), class: 'active'
		else
			content_tag :li, link_to(text, path)
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>

	<div class="row">
	<%= comment.body %>
		<%= link_to 'Edit', edit_post_comment_path(@post,comment) %> |
		<%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, confirm: 'Do you want to delete?' %>
	</div>

<% end %>

app/views/comments/_form.html.erb
<%= form_for [ @post, @comment ] do |f| %>
	<%= f.error_messages %>
	<%= f.label :body %><br/>
	<%= f.text_area :body %><br/>
	<%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<% title 'Edit comment' %>
<%= render 'form' %>
<%= link_to 'Back', post_comments_path(@post) %>

app/views/comments/index.html.erb
<% title @post.title %>
<div class="container"> 

<%= render @comments %>

<%= link_to 'New Comment', new_post_comment_path(@post) %> |
<%= link_to 'All posts', posts_path %>
</div>

app/views/comments/new.html.erb
<% title "New Post for #{@post.title}" %>
<%= render 'form' %>
<%= link_to 'Back', post_comments_path(@post) %>

app/views/comments/show.html.erb
<% title @comment.title %>
<%= render @comment %>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="collapse navbar-collapse" id="navbar-collapse1">

			<ul class="nav navbar-nav">
				<%= nav_link 'Welcome', welcome_path %>
				<% if current_user %>
					<%= nav_link 'Posts', posts_path %>
				<% end %>
			</ul>

			<ul class="nav navbar-nav pull-right">
				<% if current_user %>
					<%= nav_link 'Sign Out', sign_out_path %>
				<% else %>
					<%= nav_link 'Register', sign_up_path %>
					<%= nav_link 'Sign In', sign_in_path %>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

<div class="container-fluid">
<header class="page-header">
	<h1 class="blog-title">Group</h1>
</header>

<% flash.each do |name, msg| %>
			<div class="alert alert-<%= name == :notice ? 'success' : 'danger' %> alert-dismissable">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<%= msg %>
			</div>
	<% end %>

<%= yield %>
</div>
</div>
<div id="footer"> 
	<div class="container">
		<p class="text-muted"> &copy Joohan Lee </p>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<div class="container">
	<%= f.error_messages error_message: "Error is found" %>
<div class="row">
<div class="col-md-7">
	<%= f.label :title %>	<%= f.text_field :title, class: 'form-control col-md-3'%>
</div>
</div>
<div class="row">
<div class="col-md-7">
	<%= f.label :content %>
	<%= f.text_area :content, class: 'form-control rows-3', rows:"5" %>
</div>
</div>
	<!-- <%= f.label :date %>
	<%= f.datetime_select :date %> <br> -->
<br/>
<div class="row">
<div class="col-xs-2">

	<%= f.submit "Post it", class: 'btn btn-lg btn-primary btn-block' %>
</div>


<% end %>

app/views/posts/_post.html.erb
<%= div_for post do %>


	 <h2><%= link_to_unless_current post.title, post_path(post) %></h2>

<% end %>

app/views/posts/edit.html.erb
<% title 'Edit Post'%>

<%= render 'form' %>

<p><%= link_to 'Back', post_path(@post) %> | 
<%= link_to 'View All Posts', posts_path %> </p>

app/views/posts/index.html.erb
<% title 'Posts' %>



<table class="table table-striped table-bordered">
<tr>
	<th>Number</th>
	<th>Title</th>
	<th>Written By</th>
	<th>Date</th>
</tr>
<% @posts.each do |p| %>
<tr>
<td>
<%= p.id %>
</td>
<td>
<%= render p %>
</td>
<td>Author</td>
<td><%= p.created_at - (10*3600) %></td>
</tr>
<% end %>
</table>

<div class="col-md-1">
	<%= link_to 'New post', new_post_path, class: "btn btn-lg btn-primary btn-block" %>
</div>

app/views/posts/new.html.erb
<% title 'New Post' %>
<div class="form">
<%= render 'form' %>

<div class="col-md-1">
<%= link_to 'Back', posts_path, class: 'btn btn-lg btn-primary btn-block' %>
</div>
</div>

app/views/posts/show.html.erb
<% title @post.title %>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="highlight">
				<%= render partial: 'post', locals: {post: @post} %>
				<pre>
					<p><%= @post.content %></p>
				</pre>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="btn-group btn-group-justified">
				<div class="btn-group">
					<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary" %>
				</div>
 				<div class="btn-group">
 					<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Do you want to delete it?'}, class: "btn btn-success" %>
 				</div>
				<div class="btn-group">
					<%= link_to 'View All Posts', posts_path, class: "btn btn-info" %>
				</div>
			</div>
		</div>	
	</div>
	-------------------------------------- <!-- how can I use a style only for this page? -->
	<div class="row">
		<div class="col-md-3">
			<%= link_to 'Make a Comment', new_post_comment_path(@post), class: "btn btn-success" %>
		</div>
	</div>
<div class="container">

<%= render @post.comments %>
</div>

</div>

app/views/site/index.html.erb
<h1>Site#index</h1>
<p>Find me in app/views/site/index.html.erb</p>

app/views/site/welcome.html.erb
<% title 'Welcome' %>

<div>


	<% if current_user %>
		
					
	<% else %>
		<p>Welcome to visit my website. To get in, please log in</p>
	<% end %>



</div>

app/views/users/new.html.erb
<% title 'Sign Up' %>

<%= form_for @user do |f| %>
<div class="container">
	<form class="form-signin" role="form">
		<h2 class="form-signin-heading">Please sign up</h2>
		<div class="col-md-4">
		<%= f.error_messages error_message: "You are not registered" %>
 			Name: <%= f.text_field :name, class:"form-control" %>
			Email: <%= f.text_field :email,class:"form-control" %>
			Password: <%= f.password_field :password,class:"form-control" %>
			Confirm password: <%= f.password_field :password_confirmation, label: 'Confirm Password',class:"form-control" %><br/>
			<%= f.submit 'Sign up', class: 'btn btn-lg btn-primary btn-block' %>
		</div>
	</form>
</div>
<% end %>